
program_status = "NONE"
# NONE, FILE_SELECTED, VIDEO_TO_AUDIO_CONVERTING, AUDIO_UPLOADING, TRANSCRIBING, SAVING_JSON, TRANSCRIPT_DONE
# DETECTING_QUESTIONS, QUESTIONS_DETECTED

#PREPARING_FOR_FINDING_ANSWERS, FINDING_ANSWERS, ANSWERS_FOUND
#GENERATING_DOCUMENTS

#VIDEO_UPLOADING, VIDEO_UPLOADED
#TRANSCRIPT_UPLOADING, TRANSCRIPT_UPLOADED
#DOCUMENT_UPLOADING, DOCUMENT_UPLOADED
#CHAT_QA_UPLOADING, CHAT_QA_UPLOADED
#MANUAL_QA_UPLOADING, MANUAL_QA_UPLOADED


video_to_audio_convert_progress = 0